version: "3.9"

services:
  endpoint:
    image: nginx:latest
    platform: ${ARCHITECTURE_PLATFORM}
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file: .env
    environment:
      HOST_DOMAIN: ${HOST_DOMAIN}
    volumes:
      - ./configuration/endpoint/templates:/etc/nginx/templates:ro
      - ./configuration/endpoint/locations:/etc/nginx/locations:ro
      - ./configuration/certbot/www:/var/www/certbot/:ro
      - letsencrypt_certs:/etc/nginx/ssl/:ro
    networks:
      - backend-network

  certbot-endpoint:
    image: nginx:latest
    platform: ${ARCHITECTURE_PLATFORM}
    ports:
      - 80:80
    env_file: .env
    environment:
      HOST_DOMAIN: ${HOST_DOMAIN}
    volumes:
      - ./configuration/endpoint/templates/site.conf.template:/etc/nginx/templates/site.conf.template:ro
      - ./configuration/certbot/www:/var/www/certbot/:ro
      - letsencrypt_certs:/etc/nginx/ssl/:ro
    networks:
      - backend-network

  certbot:
    image: certbot/certbot:latest
    platform: ${ARCHITECTURE_PLATFORM}
    volumes:
      - ./configuration/certbot/www/:/var/www/certbot/:rw
      - letsencrypt_certs:/etc/letsencrypt/:rw
    networks:
      - backend-network
    depends_on:
      - certbot-endpoint

volumes:
  letsencrypt_certs:
    name: letsencrypt_certs

networks:
  backend-network:
    name: backend-network
    driver: bridge
